version: '3.8'

services:
  weaviate:
    build:
      context: .
      dockerfile: Dockerfile.railway
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      # Core Configuration
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:-true}
      AUTHENTICATION_APIKEY_ENABLED: ${AUTHENTICATION_APIKEY_ENABLED:-false}
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${AUTHENTICATION_APIKEY_ALLOWED_KEYS:-}
      AUTHENTICATION_APIKEY_USERS: ${AUTHENTICATION_APIKEY_USERS:-}
      AUTHORIZATION_ADMINLIST_ENABLED: ${AUTHORIZATION_ADMINLIST_ENABLED:-false}
      AUTHORIZATION_ADMINLIST_USERS: ${AUTHORIZATION_ADMINLIST_USERS:-}
      
      # Query Configuration
      QUERY_DEFAULTS_LIMIT: ${QUERY_DEFAULTS_LIMIT:-25}
      QUERY_MAXIMUM_RESULTS: ${QUERY_MAXIMUM_RESULTS:-10000}
      
      # Vectorizer Modules
      DEFAULT_VECTORIZER_MODULE: ${DEFAULT_VECTORIZER_MODULE:-none}
      ENABLE_MODULES: ${ENABLE_MODULES:-}
      
      # Performance Configuration
      GOMAXPROCS: ${GOMAXPROCS:-2}
      GOMEMLIMIT: ${GOMEMLIMIT:-1GiB}
      LIMIT_RESOURCES: ${LIMIT_RESOURCES:-false}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FORMAT: ${LOG_FORMAT:-json}
      
      # Cluster Configuration (for future scaling)
      CLUSTER_HOSTNAME: ${CLUSTER_HOSTNAME:-weaviate-node}
      CLUSTER_GOSSIP_BIND_PORT: ${CLUSTER_GOSSIP_BIND_PORT:-7946}
      CLUSTER_DATA_BIND_PORT: ${CLUSTER_DATA_BIND_PORT:-7947}
      
      # Backup Configuration (optional)
      BACKUP_FILESYSTEM_PATH: ${BACKUP_FILESYSTEM_PATH:-/var/lib/weaviate/backups}
      BACKUP_S3_BUCKET: ${BACKUP_S3_BUCKET:-}
      BACKUP_S3_ENDPOINT: ${BACKUP_S3_ENDPOINT:-}
      BACKUP_S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      BACKUP_S3_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      BACKUP_S3_USE_SSL: ${BACKUP_S3_USE_SSL:-true}
      
      # Module-specific configurations
      TRANSFORMERS_INFERENCE_API: ${TRANSFORMERS_INFERENCE_API:-}
      OPENAI_APIKEY: ${OPENAI_APIKEY:-}
      COHERE_APIKEY: ${COHERE_APIKEY:-}
      HUGGINGFACE_APIKEY: ${HUGGINGFACE_APIKEY:-}
      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-8080}/v1/.well-known/ready"]
      interval: 30s
      timeout: 3s
      start_period: 30s
      retries: 3

volumes:
  weaviate_data:
    driver: local
