# Railway configuration for Weaviate

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/bin/weaviate --host 0.0.0.0 --port $PORT --scheme http"
healthcheckPath = "/v1/.well-known/ready"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
region = "us-west1"

[[deploy.volumes]]
mount = "/var/lib/weaviate"
name = "weaviate-data"

[variables]
PERSISTENCE_DATA_PATH = "/var/lib/weaviate"
AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = "true"
QUERY_DEFAULTS_LIMIT = "25"
DEFAULT_VECTORIZER_MODULE = "none"
CLUSTER_HOSTNAME = "weaviate-node"
ENABLE_MODULES = ""
LOG_LEVEL = "info"
LOG_FORMAT = "json"
LIMIT_RESOURCES = "false"
GOMAXPROCS = "2"
GOMEMLIMIT = "1GiB"
